spring:
  application:
    name: learn
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa: # JPA 配置
    database: mysql
    show-sql: true
    #redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
     pool:
      max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 10
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
  timeout: 1000

redisson:
  address: redis://127.0.0.1:6379

  quartz:
    # quartz 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10 # 开启10个线程
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
# Swagger界面内容配置
swagger:
  title: TMax API接口文档
  description: TMax Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://www.sscai.club
  contact:
    name: niceyoo
    url: https://www.sscai.club
    email: apkdream@163.com


